// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Services.DBContexts;

#nullable disable

namespace Services.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Services.DbDataModel.TaskInfo", b =>
                {
                    b.Property<decimal>("TASK_ID")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("DUE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("STATUS")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TASK_DESC")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TASK_TITLE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("TASK_ID");

                    b.ToTable("TBL_TASK_DTLS");
                });
#pragma warning restore 612, 618
        }
    }
}
